### ISSUE TITLE
Re-theme, and add new features.

### ISSUE THREAD

**Issue by dirtyformal** [vatnz-dev/sops#13]
Material for MkDocs has evolved quite a bit now, and has added some features that we can benefit from greatly.

### To do:

- [x]  Bump MkDocs to latest version: #14 and #25
- [x]  Re-evaluate theme, and align to [TailwindCSS](https://tailwindcss.com/docs/customizing-colors)'s palette.
- [x]  [Configure a light and dark mode](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/) #25 
- [ ]  Investigate the addition of [rich-content search](https://squidfunk.github.io/mkdocs-material/blog/2021/09/13/search-better-faster-smaller/)
- [ ]  [Add social media cards for when links are shared on Discord](https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/)
- [x]  Re-evaluate home page (potential redesign) #25
