### ISSUE TITLE
Add Procedural Towers

### ISSUE THREAD

**Issue by mwr2410** [vatnz-dev/sops#87]
## Sub-issues:

- [ ] https://github.com/vatnz-dev/sops/issues/83
- [x] https://github.com/vatnz-dev/sops/pull/43
- [x] https://github.com/vatnz-dev/sops/pull/61
- [x] https://github.com/vatnz-dev/sops/issues/85
- [ ] https://github.com/vatnz-dev/sops/issues/84
- [ ] https://github.com/vatnz-dev/sops/issues/86

## Additional Content

- [ ] https://github.com/vatnz-dev/sops/pull/68
