### ISSUE TITLE
Add Class D Aerodromes

### ISSUE THREAD

**Issue by mwr2410** [vatnz-dev/sops#88]
## Sub-issues

- [ ] https://github.com/vatnz-dev/sops/issues/91
- [ ] https://github.com/vatnz-dev/sops/issues/92
- [ ] https://github.com/vatnz-dev/sops/issues/93
- [x] https://github.com/vatnz-dev/sops/issues/94
- [ ] https://github.com/vatnz-dev/sops/issues/95
- [ ] https://github.com/vatnz-dev/sops/pull/27
- [x] https://github.com/vatnz-dev/sops/pull/2
